name: track_your_yumi
description: "Track Your Yumi is a website/ app that displays my current status"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_vibrate: ^1.3.0
  shared_preferences: ^2.1.1
  vibration: ^1.7.5
  package_info_plus: ^4.2.0
  flutter_advanced_drawer: ^1.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Regular.ttf
        - asset: fonts/Quicksand-Bold.ttf
          weight: 700
        - asset: fonts/Quicksand-Light.ttf
          weight: 300